{% set name = "sbt" %}
{% set version = "1.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # This is the packaged jar. Not the source. We do not build from source because
  # that requires... sbt. It is a package build by itself. Since it is a jar, this
  # should not matter as it is essentially noarch.
  url: https://github.com/sbt/sbt/releases/download/v{{ version }}/sbt-{{ version }}.tgz
  sha256: 2efae0876119af7bfce8b3621b43b08c51381352916ac9de6156b1251ec26d45

build:
  number: 0
  # Since this is a java package, installation can also happen on Windows. However, the current maintainer can not test that.
  skip: true  # [not unix]

requirements:
  host:
    - coreutils  # build.sh uses ln --relative
  run:
    # OpenJDK 8 or 11 is required as stated in the sbt documentation.
    - openjdk =8|11

test:
  commands:
    - bash -c 'sbt --help | grep Usage'  # sbt --help gives exit code 1
    # sbt-create prevents warning when there is no project or build.sbt present
    - sbt --sbt-create --version

about:
  home: https://www.scala-sbt.org
  license: Apache-2.0
  license_file: LICENSE
  summary: sbt is a build tool for Scala, Java, and more.
  doc_url: https://www.scala-sbt.org/1.x/docs/
  dev_url: https://github.com/sbt/sbt

extra:
  recipe-maintainers:
    - rhpvorderman
